ID: 288147578485358592
User ID: 24356039
Time: 1357534710
Source: TweetDeck
Other: {"id":"288147578485358592","truncated":false,"in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"retweet_count":0,"entities":{"hashtags":[],"urls":[],"user_mentions":[{"screen_name":"djangoproject","name":"Django","id":"191225303","id_str":"191225303","indices":[47,61]}]},"favorited":false,"retweeted":false,"coordinates":null,"geo":null,"place":null}
-------------------------------------------------------
Well that's the first time I've managed to get @djangoproject to throw a Bus error and crash....
